import Head from 'next/head'

const Layout = ({ children, title = "Crypto Spy" }) => {
  return (
    <div className="layout">
      <Head>
        <title>{ title }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="header">
        <h1 className="coin_title"> { title }</h1>
      </header>
      <main>{ children }</main>
    </div>
 )
};

export default Layout;